# Generated by Django 3.1.1 on 2020-10-22 03:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotSocialInvStandardtime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_text', models.CharField(max_length=200, verbose_name='阶段')),
                ('index', models.IntegerField(verbose_name='序号')),
                ('name_text', models.CharField(max_length=200, verbose_name='事项')),
                ('content_text', models.CharField(max_length=200, verbose_name='具体工作')),
                ('node_text', models.CharField(max_length=200, verbose_name='节点')),
                ('time', models.IntegerField(verbose_name='单项时长')),
                ('time_to_begin', models.IntegerField(verbose_name='总时长')),
                ('dock_apartment_txt', models.CharField(max_length=200, verbose_name='责任部门')),
                ('description', models.CharField(max_length=200, verbose_name='要求/注意事项/备注')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '非社会投资项目标准工期',
                'verbose_name_plural': '非社会投资项目标准工期',
                'ordering': ('phase_text', 'index'),
            },
        ),
    ]
