# Generated by Django 3.1.1 on 2020-10-23 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standardtime', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='请输入项目时间')),
                ('pub_date', models.DateTimeField(null=True, verbose_name='发布时间')),
            ],
        ),
    ]
