# Generated by Django 3.1.1 on 2020-10-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standardtime', '0003_auto_20201023_0350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectdetail',
            options={'ordering': ('id',), 'verbose_name': '创建项目', 'verbose_name_plural': '创建项目'},
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='pub_date',
            field=models.DateField(null=True, verbose_name='请输入拿地时间，格式为 YYYY/MM/DD'),
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='假期名称')),
                ('begin_date', models.DateField(verbose_name='开始时间')),
                ('end_date', models.DateField(verbose_name='结束时间')),
            ],
            options={
                'verbose_name': '假期时间',
                'verbose_name_plural': '假期时间',
                'ordering': ('id',),
                'unique_together': {('title', 'begin_date')},
            },
        ),
    ]
