# Generated by Django 3.1.1 on 2020-10-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standardtime', '0005_holiday_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='title',
            field=models.CharField(choices=[('y', '元旦节'), ('c', '春节'), ('q', '清明节'), ('l', '劳动节'), ('d', '端午节'), ('z', '中秋节'), ('g', '国庆节')], default='y', max_length=10, verbose_name='假期名称'),
        ),
    ]
