# Generated by Django 3.1.1 on 2020-10-23 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standardtime', '0006_auto_20201023_1103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holiday',
            options={'ordering': ('begin_date',), 'verbose_name': '假期时间', 'verbose_name_plural': '假期时间'},
        ),
    ]
