# Generated by Django 3.1.1 on 2020-11-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standardtime', '0007_auto_20201023_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='notsocialinvstandardtime',
            name='isSocial',
            field=models.BooleanField(default=True, verbose_name='是否社会投资'),
        ),
    ]
