# Generated by Django 3.1.1 on 2020-11-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standardtime', '0008_notsocialinvstandardtime_issocial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notsocialinvstandardtime',
            name='isSocial',
            field=models.BooleanField(verbose_name='是否社会投资'),
        ),
    ]
