# Generated by Django 3.1.1 on 2020-11-03 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standardtime', '0009_auto_20201103_0738'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NotSocialInvStandardtime',
            new_name='InvStandardtime',
        ),
    ]
