# Generated by Django 3.1.1 on 2020-11-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standardtime', '0011_auto_20201104_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetail',
            name='isSocial',
            field=models.BooleanField(verbose_name='是否社会投资'),
        ),
    ]
