# Generated by Django 3.1.1 on 2020-12-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standardtime', '0013_auto_20201104_0554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectdetail',
            options={'ordering': ('id',), 'verbose_name': '项目', 'verbose_name_plural': '项目'},
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='title',
            field=models.CharField(db_index=True, max_length=200, unique=True, verbose_name='请输入项目名称'),
        ),
    ]
