# Generated by Django 3.1.1 on 2021-01-04 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standardtime', '0017_auto_20210104_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invstandardtime',
            name='cert_name',
            field=models.CharField(max_length=200, verbose_name='取得成绩（证照）'),
        ),
    ]
