# Generated by Django 3.1.1 on 2021-02-22 06:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('standardtime', '0019_auto_20210205_0813'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='请输入地区名称')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '地区',
                'verbose_name_plural': '地区',
                'ordering': ('id',),
            },
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='project',
            field=models.CharField(choices=[('石榴庄', '石榴庄'), ('test12', 'test12'), ('新国展三期', '新国展三期'), ('长辛店', '长辛店'), ('新国展三期02052', '新国展三期02052')], max_length=255, verbose_name='项目名称'),
        ),
        migrations.AlterField(
            model_name='projectcert',
            name='project_title',
            field=models.CharField(choices=[('石榴庄', '石榴庄'), ('test12', 'test12'), ('新国展三期', '新国展三期'), ('长辛店', '长辛店'), ('新国展三期02052', '新国展三期02052')], max_length=255, verbose_name='项目名称'),
        ),
    ]
