# Generated by Django 3.1.1 on 2021-02-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standardtime', '0020_auto_20210222_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='invstandardtime',
            name='district',
            field=models.CharField(default='公共', max_length=200, null=True, verbose_name='地区'),
        ),
    ]
