# Generated by Django 3.1.1 on 2021-02-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standardtime', '0021_invstandardtime_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetail',
            name='district',
            field=models.CharField(default='公共', max_length=200, null=True, verbose_name='地区'),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='district_creteria',
            field=models.CharField(default='公共', max_length=200, null=True, verbose_name='使用地区标准'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='area_on_floor',
            field=models.PositiveIntegerField(null=True, verbose_name='地上建筑规模'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='pub_date',
            field=models.DateField(null=True, verbose_name='拿地时间，格式为 YYYY/MM/DD'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='title',
            field=models.CharField(db_index=True, max_length=200, unique=True, verbose_name='项目名称'),
        ),
    ]
