# Generated by Django 3.1.1 on 2021-02-22 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standardtime', '0022_auto_20210222_0733'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invstandardtime',
            unique_together={('cert_name', 'isSocial', 'district')},
        ),
    ]
