# Generated by Django 3.1.1 on 2020-09-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='precondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_text', models.CharField(max_length=200, verbose_name='事项')),
                ('content_text', models.CharField(max_length=200, verbose_name='工作内容')),
                ('dock_apartment_txt', models.CharField(max_length=200, verbose_name='对接部门')),
                ('time_text', models.CharField(max_length=200, verbose_name='节点时长（自然日）')),
                ('description', models.CharField(max_length=200, verbose_name='要求/注意事项/备注')),
            ],
        ),
    ]
