# Generated by Django 3.1.1 on 2020-09-29 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polykfflow', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='precondition',
            new_name='PreSellCertPreCon',
        ),
    ]
