# Generated by Django 3.1.1 on 2020-09-29 11:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polykfflow', '0005_auto_20200929_0809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=200, verbose_name='事项')),
                ('dock_apartment_txt', models.CharField(max_length=200, verbose_name='对接部门')),
                ('description', models.CharField(max_length=200, verbose_name='要求/注意事项/备注')),
                ('create_date', models.DateTimeField(default=datetime.datetime(2020, 9, 29, 11, 3, 53, 764622, tzinfo=utc), verbose_name='创建时间')),
                ('update_date', models.DateTimeField(default=datetime.datetime(2020, 9, 29, 11, 3, 53, 764650, tzinfo=utc), verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '所需资料',
                'verbose_name_plural': '所需资料',
                'ordering': ('id',),
            },
        ),
        migrations.AlterModelOptions(
            name='presellcertprecon',
            options={'ordering': ('id',), 'verbose_name': '前置条件', 'verbose_name_plural': '前置条件'},
        ),
        migrations.AlterField(
            model_name='presellcertprecon',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 29, 11, 3, 53, 763850, tzinfo=utc), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='presellcertprecon',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 29, 11, 3, 53, 763954, tzinfo=utc), verbose_name='更新时间'),
        ),
    ]
