# Generated by Django 3.1.1 on 2020-09-29 11:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polykfflow', '0007_auto_20200929_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='document',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 29, 11, 26, 23, 475986, tzinfo=utc), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='document',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 29, 11, 26, 23, 476019, tzinfo=utc), verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='presellcertprecon',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 29, 11, 26, 23, 474837, tzinfo=utc), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='presellcertprecon',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 29, 11, 26, 23, 474917, tzinfo=utc), verbose_name='更新时间'),
        ),
    ]
