# Generated by Django 3.1.1 on 2020-09-30 02:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polykfflow', '0008_auto_20200929_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
        migrations.AddField(
            model_name='document',
            name='upload',
            field=models.FileField(blank=True, upload_to='uploads/presell/auth.doc', verbose_name='文件'),
        ),
        migrations.AlterField(
            model_name='document',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 2, 26, 34, 824203, tzinfo=utc), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='document',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 2, 26, 34, 824230, tzinfo=utc), verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='presellcertprecon',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 2, 26, 34, 823523, tzinfo=utc), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='presellcertprecon',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 2, 26, 34, 823564, tzinfo=utc), verbose_name='更新时间'),
        ),
    ]
