# Generated by Django 3.1.1 on 2020-09-30 02:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polykfflow', '0009_auto_20200930_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 2, 35, 23, 337635, tzinfo=utc), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='document',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 2, 35, 23, 337666, tzinfo=utc), verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='document',
            name='upload',
            field=models.FileField(blank=True, upload_to='uploads/presell/', verbose_name='文件'),
        ),
        migrations.AlterField(
            model_name='presellcertprecon',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 2, 35, 23, 336784, tzinfo=utc), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='presellcertprecon',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 2, 35, 23, 336856, tzinfo=utc), verbose_name='更新时间'),
        ),
    ]
