# Generated by Django 3.1.1 on 2020-09-30 05:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polykfflow', '0012_auto_20200930_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 5, 59, 20, 955494, tzinfo=utc), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, upload_to='media/presell/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 5, 59, 20, 955520, tzinfo=utc), verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='presellcertprecon',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 5, 59, 20, 954872, tzinfo=utc), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='presellcertprecon',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 5, 59, 20, 954914, tzinfo=utc), verbose_name='更新时间'),
        ),
    ]
