# Generated by Django 3.1.1 on 2020-10-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polykfflow', '0015_presellcertprecon_time_to_begin_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presellcertprecon',
            name='time_to_begin_text',
            field=models.IntegerField(verbose_name='拿地后时长'),
        ),
    ]
