# Generated by Django 3.1.1 on 2020-10-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polykfflow', '0016_auto_20201015_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presellcertprecon',
            name='time_text',
            field=models.IntegerField(verbose_name='节点时长'),
        ),
    ]
