# Generated by Django 3.1.1 on 2020-10-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polykfflow', '0017_auto_20201015_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.CharField(default='/', max_length=200, verbose_name='要求/注意事项/备注'),
        ),
    ]
