# Generated by Django 3.1.1 on 2020-10-19 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polykfflow', '0018_auto_20201015_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreSellCertFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '办理流程',
                'verbose_name_plural': '办理流程',
            },
        ),
    ]
